project:
  type: website
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
    - "!docs/"

website:
  title: "Stochastic Waltz"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/danielobembe/
      - icon: github
        href: https://github.com/danielobembe
      - icon: search
        id: quarto-search
    toggle: true
  sidebar:
    style: "docked"
    contents:
      - section: "Foundations"
        contents:
          - posts/foundations/intro-to-options/index.qmd
          - posts/foundations/put-call-parity/index.qmd
      - section: "Volatility Models"
      - section: "Pricing & Valuation"
      - section: "Greeks & Hedging"
        contents:
          - posts/greeks-hedging/delta-hedging-vanilla-option/index.qmd
      - section: "Numerical Methods"
      - section: "Algorithmic Trading"
        contents:
          - posts/algorithmic-trading/backtesting-a-strategy/index.qmd
          - posts/algorithmic-trading/volatility-targeting/index.qmd

format:
  html:
    theme:
      light: [litera, styles/styles.scss]
      dark: [litera, styles/styles.scss]
    toc: true
    toc-depth: 3
    reading-time: true

execute:
  freeze: auto
