project:
  type: website
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
    - "!docs/"

website:
  title: "Stochastic Waltz"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/danielobembe/
      - icon: github
        href: https://github.com/danielobembe
      - icon: search
        id: quarto-search
    toggle: true
  sidebar:
    style: "docked"
    contents:
      - section: "Foundations"
      - section: "Volatility Models"
      - section: "Pricing & Valuation"
      - section: "Greeks & Hedging"
      - section: "Numerical Methods"
      - section: "Algorithmic Trading"

format:
  html:
    theme:
      light: [litera, styles/styles.scss]
      dark: [litera, styles/styles.scss]
    toc: true
    toc-depth: 3

execute:
  freeze: auto
